CREATE DATABASE IF NOT EXISTS vpn;
USE vpn;
CREATE TABLE IF NOT EXISTS cert (
	user_id	VARCHAR(128) NOT NULL UNIQUE,
	user_fingerprint	VARCHAR(128) NOT NULL,
	user_validate	INT DEFAULT 1,
	PRIMARY KEY(user_id)
);
CREATE TABLE IF NOT EXISTS groups (
	group_id	INT NOT NULL,
	name	VARCHAR(128) NOT NULL,
	PRIMARY KEY(group_id)
);
CREATE TABLE IF NOT EXISTS groups_member (
	user_id	INT NOT NULL,
	group_id	INT NOT NULL,
	CONSTRAINT groups_member_user
	FOREIGN KEY(user_id) REFERENCES users(user_id)
);
CREATE TABLE IF NOT EXISTS users (
	id_row	INT NOT NULL,
	user_id	VARCHAR(128) NOT NULL UNIQUE,
	user_pass	VARCHAR(128) NOT NULL,
	user_pass_salt	VARCHAR(128) NOT NULL,
	PRIMARY KEY(id_row AUTOINCREMENT)
);
